[package]
name = "votesqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.8", features = ["blocking"]}
zip = "2.2.0"
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
regex = "1.11.0"
