# Makefile for Rust Project


all: check build format lint test

rust_check:
	cargo check

rust_build:
	cargo build

rust_format:
	cargo fmt

rust_lint:
	cargo clippy

rust_test:
	cargo test

rust_release:
	cargo build --release


